databases:
  - name: recipe_app_db
    databaseName: recipe_app_db
    user: recipe_app

services:
  - type: web
    name: recipe_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
